#prod hors infra = dev03
restic_repo: "sftp:mjouhari@87.106.192.195:/home/mjouhari/devs/dev03"
restic_password: "5225m_jouhari"
backup_paths:
  - /api-lyon
backup_time: "12:36"
user_password: "7sXm:D72oR{j]IK\"7[o}" #sudo admin password eventually unused cuz we gave necessary privileges to mjouhari
#sftp_password: "7sXm:D72oR{j]IK\"7[o}"